import { Button, Card, GradientText, Metric, PageHeader, Status, workspaceStyles as s } from '../../components/workspace/WorkspaceUI';

function AdminAuditPage() {
  return (
    <>
      <PageHeader admin eyebrow="Admin only • Companies & audit" title={<>Companies & <GradientText>audit log.</GradientText></>} description="Review organization accounts, admin actions, role changes, financial approvals, and security-sensitive configuration history." action={<Button variant="outline">Export audit</Button>} />
      <div className={s.gridFour}><Metric admin label="Organizations" value="184" note="12 pending verification"/><Metric admin label="Admin actions" value="1,942" note="Last 30 days"/><Metric admin label="Critical changes" value="17" note="Last 7 days"/><Metric admin label="Audit coverage" value="100%" note="Tracked controls"/></div>
      <div className={s.gridTwo} style={{marginTop:16}}><Card accent admin><h2>Organizations</h2><div className={s.tableWrap}><table className={s.table}><thead><tr><th>Organization</th><th>Type</th><th>Status</th><th>Leagues</th></tr></thead><tbody><tr><td>Capital Esports LLC</td><td>Organizer</td><td><Status tone="live">Verified</Status></td><td>4</td></tr><tr><td>UMBC Gaming Club</td><td>Campus</td><td><Status tone="live">Verified</Status></td><td>2</td></tr><tr><td>Atlantic Gaming Group</td><td>Organizer</td><td><Status tone="warning">Review</Status></td><td>6</td></tr></tbody></table></div></Card><Card accent admin><h2>Audit categories</h2><div className={s.list}><div className={s.listRow}><span>Role / access changes</span><b>34%</b></div><div className={s.listRow}><span>Financial approvals</span><b>27%</b></div><div className={s.listRow}><span>Integrity decisions</span><b>21%</b></div><div className={s.listRow}><span>Platform configuration</span><b>18%</b></div></div></Card></div>
      <section className={s.section}><Card accent admin><div className={s.kpiRow}><div><h2>Recent administrative actions</h2><p className={s.muted}>Simulated immutable-style activity history.</p></div><div className={s.field}><input placeholder="Search audit log..."/></div></div><div className={s.tableWrap} style={{marginTop:12}}><table className={s.table}><thead><tr><th>Time</th><th>Admin</th><th>Action</th><th>Target</th><th>Result</th></tr></thead><tbody><tr><td>14:32</td><td>A. Rivera</td><td>Role changed</td><td>user_10428</td><td>Success</td></tr><tr><td>13:58</td><td>M. Chen</td><td>Payout approved</td><td>Capital Clash</td><td>Success</td></tr><tr><td>13:11</td><td>A. Rivera</td><td>Integrity case resolved</td><td>CASE-4821</td><td>Success</td></tr><tr><td>12:46</td><td>S. Patel</td><td>Feature flag changed</td><td>Sponsor marketplace</td><td>Success</td></tr></tbody></table></div></Card></section>
    </>
  );
}
export default AdminAuditPage;
